export const SET_ALL_JOURNALS = 'NOTES/SET_ALL_JOURNALS'
export const SET_CUR_JOURNAL = 'NOTES/SET_CUR_JOURNAL'
export const SET_CUR_NOTE = 'NOTES/SET_CUR_NOTE'
export const SET_CUR_BOTH = 'NOTES/SET_CUR_BOTH'
export const SAVE_TO_POUCH = 'NOTES/SAVE_CHANGING_TO_POUCH'

export const SAGA_READ_ALL_JOURNALS = 'SAGA/NOTES/READ_ALL_JOURNALS'
export const SAGA_CREATE_JOURNAL = 'SAGA/NOTES/CREATE_JOURNAL'
export const SAGA_READ_JOURNAL = 'SAGA/NOTES/READ_JOURNAL'
export const SAGA_UPDATE_JOURNAL = 'SAGA/NOTES/UPDATE_JOURNAL'
export const SAGA_DELETE_JOURNAL = 'SAGA/NOTES/DELETE_JOURNAL'
export const SAGA_CREATE_NOTE = 'SAGA/NOTES/CREATE_NOTE'
export const SAGA_READ_NOTE = 'SAGA/NOTES/READ_NOTE'
export const SAGA_UPDATE_NOTE = 'SAGA/NOTES/UPDATE_NOTE'
export const SAGA_DELETE_NOTE = 'SAGA/NOTES/DELETE_NOTE'
export const SAGA_UPDATE_ALL = 'SAGA/NOTES/UPDATE_ALL'

const NOTE_ACT = {
    SAGA_READ_ALL_JOURNALS,
    SAGA_CREATE_JOURNAL,
    SAGA_READ_JOURNAL,
    SAGA_UPDATE_JOURNAL,
    SAGA_DELETE_JOURNAL,
    SAGA_CREATE_NOTE,
    SAGA_READ_NOTE,
    SAGA_UPDATE_NOTE,
    SAGA_DELETE_NOTE,
    SAGA_UPDATE_ALL,
}

export default NOTE_ACT